# Practice on NumPy and pandas

Here are some task for you, to refresh what you saw in the notebooks before.

It will help you strengthen the **learning objectives** from the notebook before. You should be able to
- create NumPy arrays
- manipulate them with basic mathematics operators
- extract rows, columns and items by indexing
- use aggregation methods (like sum, min, max, std) on NumPy arrays


## Part 1: Creating NumPy arrays.

1. Please create a NumPy array from the list:
```Python
my_list = [1, 2, 5, 6, 8]
````

- Please create a numpy array containing the values from 1 to 10.
-  Please create a numpy array from 0 to 5 with a step size of 0.2
- Create a numpy array with the shape 2,3 with random values


In [2]:
import numpy as np
my_list = [1, 2, 5, 6, 8]
my_array = np.array(my_list)
my_array


array([1, 2, 5, 6, 8])

2. Please create a NumPy array containing the values from 1 to 10.


In [6]:
range_arr = np.arange(1, 11)
range_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

3. Please create a NumPy array from 0 to 5 with a step size of 0.2


In [8]:
ra2 = np.arange(0, 5.2, 0.2)
ra2

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ])

4. Create a NumPy array with the shape 2,3 with random values


In [9]:
random = np.random.rand(2, 3)
random

array([[0.64075276, 0.74535006, 0.15326015],
       [0.42919133, 0.49933735, 0.24531467]])

## Part 2: Manipulate NumPy arrays.

1. Please create a NumPy array with (1, 3, '4', 7, 12, '0'). Define the content as integer.


In [10]:
myarr = np.array([1, 3, '4', 7, 12, '0'], np.int32)
myarr

array([ 1,  3,  4,  7, 12,  0], dtype=int32)

2. Check the data type of the objects and the shape of the array


In [11]:
print('Data type: ', myarr.dtype)
print('Shape: ', myarr.shape)

Data type:  int32
Shape:  (6,)


3. Update the 4th value to 30.


In [12]:
myarr[3] = 30
myarr

array([ 1,  3,  4, 30, 12,  0], dtype=int32)

4. Reshape the array to a 2x3 matrix.


In [13]:
myarr = myarr.reshape(2, 3)
myarr

array([[ 1,  3,  4],
       [30, 12,  0]], dtype=int32)

5. Please add 8 to each value in the first row and 12 to each in the second row.


In [14]:
myarr = myarr +[[8], [12]]
myarr

array([[ 9, 11, 12],
       [42, 24, 12]])

6. Multiply the first column with 2, the second with 3 and the third with 4.


In [15]:
myarr = myarr * [2, 3, 4]
myarr

array([[18, 33, 48],
       [84, 72, 48]])

7. Please sum up all numbers in the first row, and all numbers in the second row.


In [16]:
myarr.sum(axis=1)

array([ 99, 204])

8. Similarly, search for the largest number for each column.


In [17]:
myarr.max(axis=0)

array([84, 72, 48])

9. Extract the number in the second column and the first row.


In [18]:
myarr[0, 1]

np.int64(33)

10. Check at which index the value is exactly 48.

In [19]:
np.where(myarr == 48)

(array([0, 1]), array([2, 2]))